export const _TABLE = 'table'
export const _TEXTFIELD = "Text Field"
export const _TEXTAREA = "Text Area"
export const _NUMBER = "Number"
export const _PASSWORD = "Password"
export const _TITLETABLE = 'titleTable'
export const _HIDEBORDER = 'hideBorder'
export const _TRUESTRING = 'true'
export const _TAGH1 = 'h1'
export const _TAGH2 = 'h2'
export const _TAGH3 = 'h3'
export const _TAGH4 = 'h4'
export const _TAGH5 = 'h5'
export const _TAGH6 = 'h6'
export const _TAGHP = 'p'
export const _CENTER = 'center'
export const _LEFT = 'left'
export const _RIGHT = 'right'
export const _NOTDISPLAY = 'notDisplay'
export const _HTMLELEMENT = 'htmlelement'